
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-06T16:55:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "24a9b4237237d849348078ac67d5aaaf7668d5b3",
 "version": "2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
